/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimeRouteImport } from './routes/time'
import { Route as MattersRouteImport } from './routes/matters'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsPerformanceRouteImport } from './routes/settings.performance'
import { Route as SettingsCategoriesRouteImport } from './routes/settings.categories'

const TimeRoute = TimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersRoute = MattersRouteImport.update({
  id: '/matters',
  path: '/matters',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPerformanceRoute = SettingsPerformanceRouteImport.update({
  id: '/settings/performance',
  path: '/settings/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCategoriesRoute = SettingsCategoriesRouteImport.update({
  id: '/settings/categories',
  path: '/settings/categories',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/matters': typeof MattersRoute
  '/time': typeof TimeRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/performance': typeof SettingsPerformanceRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/matters': typeof MattersRoute
  '/time': typeof TimeRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/performance': typeof SettingsPerformanceRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/matters': typeof MattersRoute
  '/time': typeof TimeRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/performance': typeof SettingsPerformanceRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bills'
    | '/clients'
    | '/dashboard'
    | '/matters'
    | '/time'
    | '/settings/categories'
    | '/settings/performance'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bills'
    | '/clients'
    | '/dashboard'
    | '/matters'
    | '/time'
    | '/settings/categories'
    | '/settings/performance'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/bills'
    | '/clients'
    | '/dashboard'
    | '/matters'
    | '/time'
    | '/settings/categories'
    | '/settings/performance'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillsRoute: typeof BillsRoute
  ClientsRoute: typeof ClientsRoute
  DashboardRoute: typeof DashboardRoute
  MattersRoute: typeof MattersRoute
  TimeRoute: typeof TimeRoute
  SettingsCategoriesRoute: typeof SettingsCategoriesRoute
  SettingsPerformanceRoute: typeof SettingsPerformanceRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/time': {
      id: '/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof TimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters': {
      id: '/matters'
      path: '/matters'
      fullPath: '/matters'
      preLoaderRoute: typeof MattersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/performance': {
      id: '/settings/performance'
      path: '/settings/performance'
      fullPath: '/settings/performance'
      preLoaderRoute: typeof SettingsPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/categories': {
      id: '/settings/categories'
      path: '/settings/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof SettingsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillsRoute: BillsRoute,
  ClientsRoute: ClientsRoute,
  DashboardRoute: DashboardRoute,
  MattersRoute: MattersRoute,
  TimeRoute: TimeRoute,
  SettingsCategoriesRoute: SettingsCategoriesRoute,
  SettingsPerformanceRoute: SettingsPerformanceRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
